-- MySQL Script generated by MySQL Workbench
-- 10/15/15 14:24:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banhang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banhang` ;
CREATE SCHEMA IF NOT EXISTS `banhang` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `banhang` ;

-- -----------------------------------------------------
-- Table `banhang`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`shop` ;

CREATE TABLE IF NOT EXISTS `banhang`.`shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `address` VARCHAR(256) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `banhang`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`user` ;

CREATE TABLE IF NOT EXISTS `banhang`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(64) NULL,
  `phone_number` VARCHAR(16) NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `confirmcode` VARCHAR(32) NULL DEFAULT 'y',
  `status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `start_date` DATETIME NOT NULL DEFAULT '2014-01-01 08:00:00',
  `end_date` DATETIME NULL DEFAULT '2020-12-31 22:00:00',
  `description` VARCHAR(500) NULL,
  `salary_by_hour` FLOAT NOT NULL DEFAULT 7692,
  `work_from` INT(2) NOT NULL DEFAULT 8,
  `work_to` INT(2) NOT NULL DEFAULT 21,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `banhang`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Employees Information';

CREATE INDEX `fk_user_shop_idx` ON `banhang`.`user` (`shop_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`provider` ;

CREATE TABLE IF NOT EXISTS `banhang`.`provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(16) NOT NULL,
  `address` VARCHAR(245) NULL,
  `description` VARCHAR(245) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`import_facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`import_facture` ;

CREATE TABLE IF NOT EXISTS `banhang`.`import_facture` (
  `code` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(1000) NULL,
  `provider_id` INT NOT NULL,
  `deadline` DATETIME NULL,
  `link` VARCHAR(255) NULL,
  PRIMARY KEY (`code`),
  CONSTRAINT `fk_import_facture_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `banhang`.`provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `code_UNIQUE` ON `banhang`.`import_facture` (`code` ASC);

CREATE INDEX `fk_import_facture_provider1_idx` ON `banhang`.`import_facture` (`provider_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`provider_paid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`provider_paid` ;

CREATE TABLE IF NOT EXISTS `banhang`.`provider_paid` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider_id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_provider_paid_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `banhang`.`provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_provider_paid_provider1_idx` ON `banhang`.`provider_paid` (`provider_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`category` ;

CREATE TABLE IF NOT EXISTS `banhang`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`season` ;

CREATE TABLE IF NOT EXISTS `banhang`.`season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATE NOT NULL,
  `end_time` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`sex` ;

CREATE TABLE IF NOT EXISTS `banhang`.`sex` (
  `id` INT NOT NULL,
  `name` VARCHAR(6) NOT NULL DEFAULT 'woman',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`brand` ;

CREATE TABLE IF NOT EXISTS `banhang`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`product` ;

CREATE TABLE IF NOT EXISTS `banhang`.`product` (
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(245) NOT NULL,
  `category_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  `sex_id` INT NOT NULL,
  `export_price` FLOAT NOT NULL,
  `description` VARCHAR(1000) NULL,
  `brand_id` INT NOT NULL,
  `sale` FLOAT NOT NULL DEFAULT 0,
  `link` VARCHAR(255) NULL,
  PRIMARY KEY (`code`),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `banhang`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_season1`
    FOREIGN KEY (`season_id`)
    REFERENCES `banhang`.`season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sex1`
    FOREIGN KEY (`sex_id`)
    REFERENCES `banhang`.`sex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `banhang`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `code_UNIQUE` ON `banhang`.`product` (`code` ASC);

CREATE INDEX `fk_product_product_type1_idx` ON `banhang`.`product` (`category_id` ASC);

CREATE INDEX `fk_product_season1_idx` ON `banhang`.`product` (`season_id` ASC);

CREATE INDEX `fk_product_sex1_idx` ON `banhang`.`product` (`sex_id` ASC);

CREATE INDEX `fk_product_brand1_idx` ON `banhang`.`product` (`brand_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`product_import`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`product_import` ;

CREATE TABLE IF NOT EXISTS `banhang`.`product_import` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_code` VARCHAR(16) NOT NULL,
  `import_facture_code` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `import_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_import_product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `banhang`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_import_import_facture1`
    FOREIGN KEY (`import_facture_code`)
    REFERENCES `banhang`.`import_facture` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_import_product1_idx` ON `banhang`.`product_import` (`product_code` ASC);

CREATE INDEX `fk_product_import_import_facture1_idx` ON `banhang`.`product_import` (`import_facture_code` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`config` ;

CREATE TABLE IF NOT EXISTS `banhang`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `label` VARCHAR(245) NULL,
  `type` ENUM('text','number','button','datetime','textarea','date','checkbox') NULL,
  `description` VARCHAR(255) NULL,
  `sort_order` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `key_UNIQUE` ON `banhang`.`config` (`key` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`fund` ;

CREATE TABLE IF NOT EXISTS `banhang`.`fund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`product_return`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`product_return` ;

CREATE TABLE IF NOT EXISTS `banhang`.`product_return` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_code` VARCHAR(16) NOT NULL,
  `quantity` INT NOT NULL,
  `date` DATETIME NULL,
  `description` VARCHAR(245) NULL,
  `provider_id` INT NOT NULL,
  `return_price` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_return_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `banhang`.`provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_return_provider1_idx` ON `banhang`.`product_return` (`provider_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`customer_reservation_histo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`customer_reservation_histo` ;

CREATE TABLE IF NOT EXISTS `banhang`.`customer_reservation_histo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` VARCHAR(45) NOT NULL DEFAULT 0,
  `status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `date` DATETIME NOT NULL,
  `complete_date` DATETIME NULL,
  `reserved_facture` VARCHAR(45) NULL,
  `complete_facture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`fund_change_histo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`fund_change_histo` ;

CREATE TABLE IF NOT EXISTS `banhang`.`fund_change_histo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fund_id` INT NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(245) NULL,
  `ratio` FLOAT NOT NULL DEFAULT 1,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_fund_change_histo_fund1`
    FOREIGN KEY (`fund_id`)
    REFERENCES `banhang`.`fund` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fund_change_histo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fund_change_histo_fund1_idx` ON `banhang`.`fund_change_histo` (`fund_id` ASC);

CREATE INDEX `fk_fund_change_histo_user1_idx` ON `banhang`.`fund_change_histo` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`spend_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`spend_category` ;

CREATE TABLE IF NOT EXISTS `banhang`.`spend_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`spend_for`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`spend_for` ;

CREATE TABLE IF NOT EXISTS `banhang`.`spend_for` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`spend_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`spend_type` ;

CREATE TABLE IF NOT EXISTS `banhang`.`spend_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`spend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`spend` ;

CREATE TABLE IF NOT EXISTS `banhang`.`spend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `spend_category_id` INT NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  `description` VARCHAR(245) NULL,
  `date` DATETIME NULL,
  `spend_for_id` INT NOT NULL,
  `spend_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_spend_spend_category1`
    FOREIGN KEY (`spend_category_id`)
    REFERENCES `banhang`.`spend_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spend_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spend_spend_for1`
    FOREIGN KEY (`spend_for_id`)
    REFERENCES `banhang`.`spend_for` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spend_spend_type1`
    FOREIGN KEY (`spend_type_id`)
    REFERENCES `banhang`.`spend_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_spend_spend_category1_idx` ON `banhang`.`spend` (`spend_category_id` ASC);

CREATE INDEX `fk_spend_user1_idx` ON `banhang`.`spend` (`user_id` ASC);

CREATE INDEX `fk_spend_spend_for1_idx` ON `banhang`.`spend` (`spend_for_id` ASC);

CREATE INDEX `fk_spend_spend_type1_idx` ON `banhang`.`spend` (`spend_type_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`product_deviation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`product_deviation` ;

CREATE TABLE IF NOT EXISTS `banhang`.`product_deviation` (
  `product_code` VARCHAR(16) NOT NULL,
  `quantity` FLOAT NOT NULL DEFAULT 0,
  `date` DATETIME NULL,
  `description` VARCHAR(245) NULL,
  CONSTRAINT `fk_product_deviation_product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `banhang`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_deviation_product1_idx` ON `banhang`.`product_deviation` (`product_code` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`news` ;

CREATE TABLE IF NOT EXISTS `banhang`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NULL,
  `date` DATETIME NULL,
  `shop_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_news_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `banhang`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_news_shop1_idx` ON `banhang`.`news` (`shop_id` ASC);

CREATE INDEX `fk_news_user1_idx` ON `banhang`.`news` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`provider_paid_fund_change_histo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`provider_paid_fund_change_histo` ;

CREATE TABLE IF NOT EXISTS `banhang`.`provider_paid_fund_change_histo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fund_change_histo_id` INT NOT NULL,
  `provider_paid_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_provider_paid_fund_change_fund_change_histo1`
    FOREIGN KEY (`fund_change_histo_id`)
    REFERENCES `banhang`.`fund_change_histo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provider_paid_fund_change_provider_paid1`
    FOREIGN KEY (`provider_paid_id`)
    REFERENCES `banhang`.`provider_paid` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_provider_paid_fund_change_fund_change_histo1_idx` ON `banhang`.`provider_paid_fund_change_histo` (`fund_change_histo_id` ASC);

CREATE INDEX `fk_provider_paid_fund_change_provider_paid1_idx` ON `banhang`.`provider_paid_fund_change_histo` (`provider_paid_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`export_facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`export_facture` ;

CREATE TABLE IF NOT EXISTS `banhang`.`export_facture` (
  `code` VARCHAR(45) NOT NULL,
  `customer_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `isonline` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`code`),
  CONSTRAINT `fk_export_facture_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `banhang`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_export_facture_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_export_facture_shop1_idx` ON `banhang`.`export_facture` (`shop_id` ASC);

CREATE INDEX `fk_export_facture_user1_idx` ON `banhang`.`export_facture` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`export_facture_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`export_facture_product` ;

CREATE TABLE IF NOT EXISTS `banhang`.`export_facture_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_code` VARCHAR(16) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `export_price` FLOAT NOT NULL DEFAULT 0,
  `export_facture_code` VARCHAR(45) NOT NULL,
  `re_qty` INT NOT NULL DEFAULT 0,
  `re_date` DATETIME NULL,
  `re_description` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_export_facture_product_product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `banhang`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_export_facture_product_export_facture1`
    FOREIGN KEY (`export_facture_code`)
    REFERENCES `banhang`.`export_facture` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_export_facture_product_product1_idx` ON `banhang`.`export_facture_product` (`product_code` ASC);

CREATE INDEX `fk_export_facture_product_export_facture1_idx` ON `banhang`.`export_facture_product` (`export_facture_code` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`export_facture_trace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`export_facture_trace` ;

CREATE TABLE IF NOT EXISTS `banhang`.`export_facture_trace` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `export_facture_code` VARCHAR(45) NOT NULL,
  `total` FLOAT NOT NULL DEFAULT 0,
  `debt` FLOAT NOT NULL DEFAULT 0,
  `reserved` FLOAT NOT NULL DEFAULT 0,
  `order` FLOAT NOT NULL DEFAULT 0,
  `customer_give` FLOAT NOT NULL DEFAULT 0,
  `give_customer` FLOAT NOT NULL DEFAULT 0,
  `bonus_used` FLOAT NOT NULL DEFAULT 0,
  `return_amount` FLOAT NOT NULL DEFAULT 0,
  `shop_id` INT NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `customer_id` INT NOT NULL,
  `bonus_ratio` FLOAT NOT NULL DEFAULT 100,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_export_facture_trace_export_facture1`
    FOREIGN KEY (`export_facture_code`)
    REFERENCES `banhang`.`export_facture` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_export_facture_trace_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `banhang`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_export_facture_trace_export_facture1_idx` ON `banhang`.`export_facture_trace` (`export_facture_code` ASC);

CREATE INDEX `fk_export_facture_trace_shop1_idx` ON `banhang`.`export_facture_trace` (`shop_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`customer_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`customer_order` ;

CREATE TABLE IF NOT EXISTS `banhang`.`customer_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_tel` VARCHAR(45) NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `product_code` VARCHAR(16) NULL,
  `color` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(255) NULL,
  `status` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`money_inout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`money_inout` ;

CREATE TABLE IF NOT EXISTS `banhang`.`money_inout` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_money_inout_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `banhang`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_money_inout_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_money_inout_shop1_idx` ON `banhang`.`money_inout` (`shop_id` ASC);

CREATE INDEX `fk_money_inout_user1_idx` ON `banhang`.`money_inout` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`inout_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`inout_type` ;

CREATE TABLE IF NOT EXISTS `banhang`.`inout_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`property` ;

CREATE TABLE IF NOT EXISTS `banhang`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0,
  `ket` FLOAT NULL DEFAULT 0,
  `loan` FLOAT NULL DEFAULT 0,
  `fund` FLOAT NULL DEFAULT 0,
  `store` FLOAT NULL DEFAULT 0,
  `debt` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`user_absent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`user_absent` ;

CREATE TABLE IF NOT EXISTS `banhang`.`user_absent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `from` VARCHAR(5) NOT NULL,
  `to` VARCHAR(5) NOT NULL,
  `reason` VARCHAR(255) NULL COMMENT 'Lý do xin nghỉ',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_absent_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_absent_user1_idx` ON `banhang`.`user_absent` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`user_salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`user_salary` ;

CREATE TABLE IF NOT EXISTS `banhang`.`user_salary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `month` VARCHAR(6) NOT NULL,
  `total_hours` FLOAT NOT NULL DEFAULT 0,
  `salary_by_hour` FLOAT NOT NULL DEFAULT 0,
  `bonus` FLOAT NOT NULL DEFAULT 0,
  `penalty` FLOAT NOT NULL DEFAULT 0,
  `description` VARCHAR(255) NULL,
  `next_pay_date` DATE NULL,
  `paid_amount` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_salary_table_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_salary_table_user1_idx` ON `banhang`.`user_salary` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`module` ;

CREATE TABLE IF NOT EXISTS `banhang`.`module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `active_sub` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`user_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`user_module` ;

CREATE TABLE IF NOT EXISTS `banhang`.`user_module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_module_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_module_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES `banhang`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_module_user1_idx` ON `banhang`.`user_module` (`user_id` ASC);

CREATE INDEX `fk_user_module_module1_idx` ON `banhang`.`user_module` (`module_id` ASC);


-- -----------------------------------------------------
-- Table `banhang`.`sub_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`sub_module` ;

CREATE TABLE IF NOT EXISTS `banhang`.`sub_module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banhang`.`module_sub_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banhang`.`module_sub_module` ;

CREATE TABLE IF NOT EXISTS `banhang`.`module_sub_module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `module_id` INT NOT NULL,
  `sub_module_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_module_sub_module_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES `banhang`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_sub_module_sub_module1`
    FOREIGN KEY (`sub_module_id`)
    REFERENCES `banhang`.`sub_module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_module_sub_module_module1_idx` ON `banhang`.`module_sub_module` (`module_id` ASC);

CREATE INDEX `fk_module_sub_module_sub_module1_idx` ON `banhang`.`module_sub_module` (`sub_module_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `banhang`.`shop`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`shop` (`id`, `name`, `address`, `date`) VALUES (1, 'shop1', '19 Vạn Phúc - Hà Đông - Hà Nội', '2014-01-01 10:00:00');
INSERT INTO `banhang`.`shop` (`id`, `name`, `address`, `date`) VALUES (2, 'shop2', 'Số 3 Ngã Tư Lê Văn Lương - Vạn Phúc - Hà Đông - Hà Nội', '2014-01-01 10:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`user` (`id`, `shop_id`, `name`, `email`, `phone_number`, `username`, `password`, `confirmcode`, `status`, `start_date`, `end_date`, `description`, `salary_by_hour`, `work_from`, `work_to`, `is_admin`) VALUES (1, 1, 'Trần Trí Duệ', 'trantridue@gmail.com', '0979355285', 'admin', '4eae18cf9e54a0f62b44176d074cbe2f', 'y', 'y', '2014-01-01 10:00:00', '2020-12-31 22:00:00', 'Ông chủ', 8000, 8, 21, 1);
INSERT INTO `banhang`.`user` (`id`, `shop_id`, `name`, `email`, `phone_number`, `username`, `password`, `confirmcode`, `status`, `start_date`, `end_date`, `description`, `salary_by_hour`, `work_from`, `work_to`, `is_admin`) VALUES (2, 2, 'Lê Thị Châu', 'chau@gmail.com', '0966807709', 'chau', '4eae18cf9e54a0f62b44176d074cbe2f', 'y', 'y', '2014-01-01 10:00:00', '2020-12-31 22:00:00', 'Bà Chủ', 8000, 8, 21, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`provider`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`provider` (`id`, `name`, `tel`, `address`, `description`, `date`) VALUES (1, 'Kiểm Hàng', '0979355285', '19 Vạn Phúc Hà Đông Hà Nội', 'Chủ cửa hàng', NULL);
INSERT INTO `banhang`.`provider` (`id`, `name`, `tel`, `address`, `description`, `date`) VALUES (2, 'Hiền', '0988774433', 'Đặng Văn Ngữ', 'Nhà cung cấp lớn', NULL);
INSERT INTO `banhang`.`provider` (`id`, `name`, `tel`, `address`, `description`, `date`) VALUES (3, 'Zamy', '0906223781', 'nghi tàm', 'Nhà cung cấp quan trọng', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`category` (`id`, `name`, `description`) VALUES (1, 'VAY', 'Các loại váy');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`season`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`season` (`id`, `start_time`, `end_time`, `name`) VALUES (1, '2014-01-01', '2014-03-31', 'SPRING');
INSERT INTO `banhang`.`season` (`id`, `start_time`, `end_time`, `name`) VALUES (2, '2014-04-01', '2014-06-30', 'SUMMER');
INSERT INTO `banhang`.`season` (`id`, `start_time`, `end_time`, `name`) VALUES (3, '2014-07-01', '2014-09-30', 'AUTUMN');
INSERT INTO `banhang`.`season` (`id`, `start_time`, `end_time`, `name`) VALUES (4, '2014-10-01', '2014-12-31', 'WINTER');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`sex`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`sex` (`id`, `name`) VALUES (1, 'woman');
INSERT INTO `banhang`.`sex` (`id`, `name`) VALUES (2, 'man');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`brand` (`id`, `name`) VALUES (1, 'MADEVN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banhang`.`fund`
-- -----------------------------------------------------
START TRANSACTION;
USE `banhang`;
INSERT INTO `banhang`.`fund` (`id`, `name`, `description`) VALUES (1, 'KÉT SẮT', 'KÉT SẮT');

COMMIT;

