<?php 
define('text','text');
define('number','number');
define('date','date');
define('datetime','datetime');
define('textarea','textarea');
define('button','button');
define('checkbox','checkbox');
define('select','select');
?>